services:
  teleop-robot:
    image: deploy:v0.1.5  # change this to your docker image
    volumes:
      - /dev/:/dev/:rmw

    entrypoint: ["/bin/bash", "/ros_entrypoint.sh"]
    command: sleep infinity
    device_cgroup_rules:
      - 'c 166:* rmw'
      - 'c 188:* rmw'
      - 'c 13:* rmw'